/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Game;
import javax.swing.*;
import javax.swing.event.TableModelEvent;
import java.io.IOException;
import Model.GameState;
import Controller.InvalidGame;

/**
 *
 * @author hassa
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form CurrentGameFrame
     */
    private Viewable view;
    private Game game;

    public GameFrame(Viewable view, Game game) {
        this.view = view;
        this.game = game;
        initComponents();
        loadBoardToTable();
        attachTableListener();
    }
private int countEmptyCells() {
    int count = 0;
    int[][] board = game.getBoard();

    for (int i = 0; i < 9; i++) {
        for (int j = 0; j < 9; j++) {
            if (board[i][j] == 0) count++;
        }
    }
    return count;
}
    private void loadBoardToTable() {
        int[][] board = game.getBoard();
        SolverButton.setEnabled(countEmptyCells() == 5);

        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                if (board[i][j] == 0) {
                    CurrentGameBoard.setValueAt("", i, j);
                } else {
                    CurrentGameBoard.setValueAt(board[i][j], i, j);
                }
            }
        }
    }

    private void attachTableListener() {
        
        CurrentGameBoard.getModel().addTableModelListener(e -> {

            if (e.getType() != TableModelEvent.UPDATE) {
                return;
            }

            int row = e.getFirstRow();
            int col = e.getColumn();

            if (row < 0 || col < 0) {
                return;
            }

            Object value = CurrentGameBoard.getValueAt(row, col);
            int newValue = 0;

            if (value != null && !value.toString().isEmpty()) {
                try {
                    newValue = Integer.parseInt(value.toString());
                } catch (NumberFormatException ex) {
                    CurrentGameBoard.setValueAt("", row, col);
                    return;
                }
            }

            cellEdited(row, col, newValue);
        });
    }

   private void cellEdited(int x, int y, int newValue) {
    int prev = game.getBoard()[x][y];
    game.getBoard()[x][y] = newValue;

    SolverButton.setEnabled(countEmptyCells() == 5);

    try {
        view.logUserAction(x + "," + y + "," + newValue + "," + prev);
        view.saveCurrentGame(game);  
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Failed to save move");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        CurrentGameBoard = new javax.swing.JTable();
        UndoButton = new javax.swing.JButton();
        SolverButton = new javax.swing.JButton();
        VerifyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Soduku!");

        CurrentGameBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(CurrentGameBoard);

        UndoButton.setText("Undo");
        UndoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoButtonActionPerformed(evt);
            }
        });

        SolverButton.setText("Solver");
        SolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolverButtonActionPerformed(evt);
            }
        });

        VerifyButton.setText("Verify");
        VerifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UndoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SolverButton)
                                .addGap(60, 60, 60)
                                .addComponent(VerifyButton)
                                .addGap(26, 26, 26)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UndoButton)
                    .addComponent(SolverButton)
                    .addComponent(VerifyButton))
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UndoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoButtonActionPerformed
        try {
            view.undo(game);
            loadBoardToTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nothing to undo");
        }
    }//GEN-LAST:event_UndoButtonActionPerformed

    private void SolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolverButtonActionPerformed
         try {
        int[] solution = view.solveGame(game);
        JOptionPane.showMessageDialog(this, "Solution exists for missing cells");
    } catch (InvalidGame e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_SolverButtonActionPerformed

    private void VerifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyButtonActionPerformed
       String result = view.verifyGame(game);
        System.out.println(result);
    if (result.equals("valid")) {
        
        JOptionPane.showMessageDialog(this, "Game solved correctly!");

        try {
            view.completeCurrentGame();
            new java.io.File(game.getDifficulty().toLowerCase()).listFiles(f -> f.getName().endsWith(".csv"))[new java.util.Random().nextInt(new java.io.File(game.getDifficulty().toLowerCase()).listFiles(f -> f.getName().endsWith(".csv")).length)].delete();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to finalize game");
        }

        dispose();
        new StarterFrame(view).setVisible(true);

    } else  {

        JOptionPane.showMessageDialog(this, "Incorrect solution");}

    }//GEN-LAST:event_VerifyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CurrentGameBoard;
    private javax.swing.JButton SolverButton;
    private javax.swing.JButton UndoButton;
    private javax.swing.JButton VerifyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
